volumes:
  mysql:
  mysql_config:

networks:
  app:

services:

  mysqldb:
    image: mysql:5.7.39
    ports:
    - 3306:3306
    environment:
      - MYSQL_USER=usr
      - MYSQL_DATABASE=simple_mvc
      - MYSQL_PASSWORD=P@ssword1
      # ! do not use this in production
      - MYSQL_ALLOW_EMPTY_PASSWORD="yes"
    volumes:
      - mysql:/var/lib/mysql
      - mysql_config:/etc/mysql
    networks:
      - app

  phpapp:
    build:
      context: .
    ports:
    - 80:80
    depends_on:
      - mysqldb
    networks:
      - app
    volumes:
      - ./:/var/www
